import type { Metadata } from "next";
import { Montserrat, Outfit } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // This matches the CSS variable above
  weight: ["700", "800"],
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",    // This matches the CSS variable above
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Proactive-Prosthetics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${outfit.variable}`}>
      {/* Adding antialiased here ensures the fonts stay sharp on all screens */}
      <body className="antialiased font-body">
        {children}
      </body>
    </html>
  );
}